### ISSUE TITLE
Axios version compatibility

### ISSUE THREAD

**Issue by gingerich** [haverstack/axios-fetch-adapter#5]
Which version of axios is this meant to be compatible with? I think you could specify this in `peerDependencies` so npm will complain if someone tries to install alongside an incompatible version of axios. Recently, axios _finally_ [released](https://github.com/axios/axios/releases/tag/v1.3.4) a major version, so this is particularly relevant now.

**Comment by cuibonobo** [comment]
This is a good callout. The reason I haven't listed it in `peerDependencies` is that for my use-case Axios _isn't_ a direct peer dependency. This library came about because I needed to use the Square SDK (v25.1) in Cloudflare Workers. That, in turn, depends `@apimatic/core` v0.9.3, and _that_ depends on Axios v0.21.1 (a 2-year-old version).

Since Axios is so nested in this structure, the last time I tried listing it in `peerDependencies` it made a mess. Though I'd appreciate advice on getting this to work.

**Comment by cuibonobo** [comment]
@gingerich I tried your suggestion and it worked fine. I guess the last time I tried `peerDependencies` I gave it a bad version that made it confused. Thanks again from bringing this to my attention.

**Comment by cuibonobo** [comment]
Fix is included in v0.7.0.

**Comment by gingerich** [comment]
@cuibonobo Thanks for the quick change. I've also had bad experiences with `peerDependencies` and managing version compatibility with `npm` in general 😞
